# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addman', '0005_auto_20160228_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='address',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='address',
            name='status',
            field=models.CharField(choices=[(b'UNPARSED', b'Not yet processed'), (b'FAILED', b'No match found'), (b'WARN', b'Tentative match, may be undeliverable'), (b'CONFIRMABLE', b'Tentative match, confirmation required'), (b'VALIDATED', b'Validated and deliverable')], default=b'UNPARSED', max_length=10),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
