# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addman', '0008_auto_20160304_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_validated',
        ),
    ]
